version: "3.8"

services:
  # LocalStack - AWS Services Emulation
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-dev
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

  # Next.js GUI Application (Development with hot reload)
  gui:
    build:
      context: .
      dockerfile: Dockerfile.gui.dev
    container_name: localstack-gui-dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3030/api
    volumes:
      - ./localstack-gui:/app
      - /app/node_modules
      - /app/.next
      - ./config:/app/config:ro
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - localstack-network
    restart: unless-stopped
    command: npm run dev

  # Express.js API Server (Development with hot reload)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: localstack-api-dev
    environment:
      - NODE_ENV=development
      - PORT=3031
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack-api:/app
      - /app/node_modules
      - ./config:/app/config:ro
      - ./logs:/app/logs
    ports:
      - "3031:3031"
    depends_on:
      - localstack
    networks:
      - localstack-network
    restart: unless-stopped
    command: npm run dev

networks:
  localstack-network:
    driver: bridge

volumes:
  localstack_data:
